# These are supported funding model platforms

github: bkimminich
patreon: bkimminich
open_collective: # Replace with a single Open Collective username
ko_fi: bkimminich
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part3/donations.html
