engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true

ratings:
   paths:
   - "**.js"
   - "**.css"

exclude_paths:
- "app/private/**/*"
- "app/css/geo-bootstrap/**/*"
- "data/datacreator.js"
- "vagrant/shake.js"
- "Gruntfile.js"
- "*conf.js"
