# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)
tasks:
  - init: npm install
    command: npm run start

ports:
  - name: Juice-Shop App
    description: The main application web server
    port: 3000
    onOpen: open-preview
