# Please adjust to your needs (see https://www.gitpod.io/docs/config-gitpod-file)
tasks:
  - init: npm install
    command: npm start

ports:
  - name: OWASP Juice Shop
    description: The Juice Shop web server
    port: 3000
    onOpen: open-preview
