language: node_js
node_js:
- 9 # recommended version
- 8
- 6
branches:
  except:
  - gh-pages
  - l10n_develop
addons:
  apt:
    packages:
      - xvfb
  chrome: stable
  code_climate:
    repo_token:
      secure: NC3ew4c92DO4SAdbJvaZkaRnEZaZcAr9NcxOeraqAKHRXY3COnerWGR8+kIE9KiadcRdatmu0sSjWldDcAZfmMwOraMI9CDkqdPSjtjciCVEFdGi+OPOvMY/gOJU6XeM7lsO5MvYD7mqChl2gR6s7IO/klPahf53c97PPDo3C90=
env:
  global:
    - DISPLAY=:99
before_install:
- rm -rf node_modules
before_script:
- npm install grunt-cli -g
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- travis_wait npm test && npm run frisby && NODE_ENV=ctf npm run protractor
after_success:
- ./node_modules/.bin/lcov-result-merger 'build/reports/coverage/*/lcov.info' 'build/reports/coverage/lcov_merged.info'
- ./node_modules/.bin/codeclimate-test-reporter < ./build/reports/coverage/lcov_merged.info
notifications:
  email:
  - secure: ADLqaNm7lR8sgCkSz7eWtWdm8zZ9OsbkcQAi2nm7hQPWAkTWPfr9qeOBh39Z3PZvkgDdlUpNZc/uPlcEGEILznJRF3HlQjWrWksNNtY3xaRc01B4uXlDbODjttb6v9mOqkwUqRfQLeerOqNynNSkT129+mz4FANn0+oucZ3EuQc=
  - secure: HhhSoqY87yd8Hkt+cfXk9XXDJeWViYQoPq8f7SJofkwSWtxfOS9GNbOUehZJDqjBMARoGi3SJBImRbisnwfMcEhKpSZs2S4Osdwk2Ayy0h8V/O+qHhiEuJq1mPbAWrYNGQerz16Ec4SbX6hPnAEle2SUwjbPUnfRRCROsJqfm0o=
  webhooks:
    urls:
    - secure: QZ3/2h7hThg527PX1z7kTTRGL5jEbTTHRbetYHt8Gzgdhvtruq4cjxMQZdUcmxKlncAhoB976iFl/Ja9EpExgrXnt/Tj0Aft6JDc7g8y0kuD/SiQpFT7d46R7vOTJeFHyMzfQN9M/h81DXrG+VO5OPGR/QYNa39kMzkTc86tt1E=
    on_success: always
    on_failure: always
    on_start: never
  slack:
    rooms:
      secure: bQlLJ6OvyWUWO51eYjPlEwuGApdYEsqBa8He4gKcTFdjTE6lLxrdu0QE6y1iIroN5+QOk4QpwIYaeWxhgrtVqTNrq9iWnhRR8agcXMPBh1cHnh8EZO6yuC3JE1dd2syKe5Vds67w6KbJedX5GNRg2SVLrL2mHq2syvWAD17BcoI=
    on_success: change
    on_failure: change
    on_start: never
before_deploy:
- rm -rf node_modules
- npm install --production
- grunt package
deploy:
- provider: heroku
  api_key:
    secure: faVT3Ne/O7lVo0+pTm6RcXss0ivvSoODaxMkiVwdpk/51/EsRd4+/Gjmp3RGPmW5H5luOephsI8uFMMhgKiu5i3NV58ZSx29Z0aby+bfIhesZGZqJQvxeW8B0J8vlQFnEHP6xc6SAlXSdNjNpDeBaV7WSFSGKGp4Nh5QyO2ySLI=
  app:
    master: juice-shop
    develop: juice-shop-staging
  on:
    repo: bkimminich/juice-shop
    node: 9
- provider: releases
  overwrite: true
  api_key:
    secure: fHybcH65ZdS5ITVKH2tIVBITVSiRQJ1AuWqLP16gyAz5pdmWbLM5gA/74zCozanRmuB+7pGFbhDNm075JWoEDVrWSFDLnNiXvfgUYa4oVEiWZlLvOfSARaU3AQPlVvFVhIbG9SA5IEwTtNFbyHjqLjGn/DSBpiIDqqxhF57vw7Q=
  file: dist/*
  skip_cleanup: true
  file_glob: true
  draft: true
  tag_name: $TRAVIS_TAG
  on:
    repo: bkimminich/juice-shop
    tags: true
