application:
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  showChallengeHints: false
  showVersionNumber: false
  showHackingInstructor: false
  showGitHubLinks: false
  welcomeBanner:
    showOnFirstStart: false
ctf:
  showFlagsInNotifications: true
