application:
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  showChallengeHints: false
  showVersionNumber: false
  gitHubRibbon: false
challenges:
  safetyOverride: true
ctf:
  showFlagsInNotifications: true
