application:
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  showCtfFlagsInNotifications: true
  showCtfCountryDetailsInNotifications: both
  showChallengeHints: false
  showVersionNumber: false
  gitHubRibbon: none
