application:
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  showCtfFlagsInNotifications: true
  shotCtfCountryDetailsInNotifications: true
  showChallengeHints: false
  showVersionNumber: false
  gitHubRibbon: none
