name: "Node.js CI"

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Cache Node.js modules"
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: "Install Angular CLI"
        run: npm install -g @angular/cli
      - name: "Install application"
        run: npm install
      - name: "Lint code and configurations"
        run: |
          npm run lint
          npm run lint:config -- -f ./config/7ms.yml
          npm run lint:config -- -f ./config/addo.yml
          npm run lint:config -- -f ./config/bodgeit.yml
          npm run lint:config -- -f ./config/ctf.yml
          npm run lint:config -- -f ./config/default.yml
          npm run lint:config -- -f ./config/fbctf.yml
          npm run lint:config -- -f ./config/juicebox.yml
          npm run lint:config -- -f ./config/mozilla.yml
          npm run lint:config -- -f ./config/oss.yml
          npm run lint:config -- -f ./config/quiet.yml
          npm run lint:config -- -f ./config/tutorial.yml
          npm run lint:config -- -f ./config/unsafe.yml
      - name: "Execute unit tests"
        run: npm test
      - name: "Execute integration tests"
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
          set NODE_ENV=test
          else
          export NODE_ENV=test
          fi
          npm run frisby
        shell: bash

